version: "3.11"

services:
  db_service:
    container_name: scm_challenge_db_service
    image: rnaranjo/scm_challenge_db_service:1.0.0
    networks:
      - backend
    build: .
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - "4001:4001"

networks:
  backend:
    name: backend
    external: true