version: "3.11"

services:
  model_service:
    container_name: scm_challenge_model_service
    image: rnaranjo/scm_challenge_model_service:1.0.0
    networks:
      - backend
    build: .
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - "4002:4002"

networks:
  backend:
    name: backend
    external: true